### ISSUE TITLE
New Ticket Error: undefined method 'name'

### ISSUE THREAD

**Issue by christine-sm** [rubyforgood/pdx_diaper#43] opened 2016-06-19 15:02 UTC
This happens when I submit a new ticket:
<img width="1058" alt="screen shot 2016-06-19 at 11 00 26 am" src="https://cloud.githubusercontent.com/assets/15206696/16178089/47da4ae0-360d-11e6-9a6e-4f6a154c0f17.png">

**Comment by armahillo** [comment] 2016-06-21 23:43
@cmmovius I created a ticket successfully and did not encounter this. Are you able to re-create this bug and if so, can you list out the steps you did to produce it? 

It's possible that this behavior was fixed by @cattywampus in the eleventh hour -- I know he did a couple commits to that feature.

**Comment by christine-sm** [comment] 2016-06-22 13:14
@armahillo I recreated this issue this morning. I went to [localhost:3000/tickets/new](http://localhost:3000/tickets/new) and tried to create the following ticket:
![screen shot 2016-06-22 at 9 10 08 am](https://cloud.githubusercontent.com/assets/15206696/16267790/9936044e-3859-11e6-923e-b50f1e4c6f8f.png)
When I hit "Create Ticket" I get the following:
![screen shot 2016-06-22 at 9 14 24 am](https://cloud.githubusercontent.com/assets/15206696/16267826/c01eb146-3859-11e6-9004-2f38174c3703.png)

**Comment by armahillo** [comment] 2016-06-22 13:16
Perfect, thanks! :+1:  I will use that info to re-attempt. Is your local repo sync'd with origin?

**Comment by christine-sm** [comment] 2016-06-22 13:26
Yep! I `git pull`ed before doing this

**Comment by armahillo** [comment] 2016-06-22 13:27
OK Excellent. I will look into this today -- thanks!

**Comment by cattywampus** [comment] 2016-06-23 04:20
Yeah, looks like the issue is definitely reproducible for tickets with blank containers (i.e., all fields for a particular container are blank). I should be able to whip up a fix for this.

**Closed as completed** 2016-06-23 13:48 UTC
Labels: bug

**Comment by armahillo** [comment] 2016-06-23 13:50
Sweet! Thanks!!!! :100:
